controller_manager:
  ros__parameters:
    update_rate: 100

    jackal_velocity_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

jackal_velocity_controller:
  ros__parameters:
    left_wheel_names: ["front_left_wheel", "rear_left_wheel"]
    right_wheel_names: ["front_right_wheel", "rear_right_wheel"]

    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

    wheel_separation: 0.266
    wheel_radius: 0.034

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 40.0
    odom_frame_id: odom
    base_frame_id: base_link
    enable_odom_tf: true
    open_loop: true

    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    cmd_vel_timeout: 0.5
    use_stamped_vel: true

    linear.x.has_velocity_limits: false
    linear.x.has_acceleration_limits: false
    linear.x.max_velocity: 200.0
    linear.x.min_velocity: -200.0
    linear.x.max_acceleration: 200.0

    angular.z.has_velocity_limits: false
    angular.z.has_acceleration_limits: false
    angular.z.max_velocity: 200.0
    angular.z.min_velocity: -200.0
    angular.z.max_acceleration: 200.0
